### ISSUE TITLE
Keyboard Shortcuts dev219

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#74] opened 2016-12-04 22:54 UTC
Keyboard shortcuts such as Shift + character appear to be disabled when entering information into the bindings.

**Comment by justparking** [comment] 2016-12-04 23:04
Yeah, I've logged this too. It's a duplicate of #63. 

@mcartmel, I'm going to pull down the latest release and roll back all recent UI changes until this one is fixed.

**Closed by justparking** 2016-12-04 23:04 UTC
Labels: bug, duplicate

**Comment by mcartmel** [comment] 2016-12-05 01:49
No need, I've resolved this now.
