### ISSUE TITLE
Scheduler sometimes misses events

### ISSUE THREAD

**Issue by keithvaz** [museumsvictoria/nodel#13] opened 2014-10-21 22:59 UTC
Error that appears on console - 
WARNING:apscheduler.scheduler:Run time of job "callevent (trigger: cron[month='_', day='_', day_of_week='*', hour='9', minute='0'], next run at: 2014-10-23 09:00:00)" was missed by 0:00:11.240000

If you manually trigger the event via Signals, it works.

This issue is quite rare in occurrence; however, it has affected all the Scheduler nodes hosted on the same machine, but running different Node hosts.

The fix is to disable then enable the Scheduler node.

**Comment by scienceworld** [comment] 2015-02-18 16:36
Got some good news.

The VM that nodel runs on was paused yesterday for a bit while we performed some server maintenance.  This caused the scheduler to miss its schedule, and run it 13 minutes late.  I think this is because the scheduler isnt based on the clock, but is based on a Seconds countdown from the last time the scheduler checked for an event and is working off a delta to next event.  when the VM was paused, the countdown was paused and then resumed with the previous amount of ticks remaining.  There was no catch up or reevaluation of the delta to the next event and so the schedule ran late.

`02-17 09:14:02 - INFO:apscheduler.scheduler:Scheduler started
02-17 09:14:02 - DEBUG:apscheduler.scheduler:Looking for jobs to run
02-17 09:14:02 - DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-02-17 17:00:00 (in 27957.788001 seconds)
02-17 17:13:25 - DEBUG:apscheduler.scheduler:Looking for jobs to run
02-17 17:13:26 - DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-02-18 09:00:00 (in 56794.083000 seconds)
02-17 17:13:26 - DEBUG:apscheduler.threadpool:Started worker thread
02-17 17:13:26 - WARNING:apscheduler.scheduler:Ignoring lateness - "callevent (trigger: cron[month='*', day='*', day_of_week='1-4', hour='17', minute='0'], next run at: 2015-02-18 17:00:00)" was late by 0:13:26.104000
02-17 17:13:26 - INFO:apscheduler.scheduler:Running job "callevent (trigger: cron[month='*', day='*', day_of_week='1-4', hour='17', minute='0'], next run at: 2015-02-18 17:00:00)" (scheduled at 2015-02-17 17:00:00)
02-17 17:13:26 - calling: AllOff
02-17 17:13:26 - INFO:apscheduler.scheduler:Job "callevent (trigger: cron[month='*', day='*', day_of_week='1-4', hour='17', minute='0'], next run at: 2015-02-18 17:00:00)" executed successfully
02-17 17:13:27 - DEBUG:apscheduler.threadpool:Exiting worker thread`

**Comment by mcartmel** [comment] 2017-03-22 03:22
Generally, this appears to be caused by a problem with the underlying apscheduler module which is going to be difficult to fix.

I'm going to close this for now as we are releasing the new scheduler recipe which I believe most people will use instead of this.

In the limited occasions that this scheduler might still be used over the new recipe (like for basic standalone operation), I think the workaround is sufficient.

**Closed by mcartmel** 2017-03-22 03:22 UTC
Labels: workaround exists
