### ISSUE TITLE
End node names with extended characters in them not working

### ISSUE THREAD

**Issue by rhulse** [museumsvictoria/nodel#116] opened 2017-09-12 20:32 UTC
The nodes themselves work fine, and can be found in the type-ahead search in groups, BUT when wired up they are not actually wired up, so no signals or actions pass between the group and the end node.

For example this works fine:

`Ko Rongowhakaata - DL05 PC - Te Hau ki Turanga`

Where as this does not:

`Ko Rongowhakaata - DL05 PC - Te Hau ki Tūranga`

Note the macron on the u in Turanga.

I have not confirmed if this is also the case with group nodes.

**Comment by rhulse** [comment] 2017-09-12 20:35
@justparking This is the bug I mentioned yesterday, now confirmed.

**Comment by justparking** [comment] 2018-07-19 10:47
Belated update: I believe fixes have addressed this issue since it was reported, or I was not able to reproduce the problem.

To reproduce it I created two nodes and had them bound together.

![image](https://user-images.githubusercontent.com/5266533/42938208-d9b7ad98-8b94-11e8-8ba4-1536bf15e6ab.png)

Everything seemed to work.

Closing for now. If you see this again or can reproduce it using later versions of nodel, please reopen.

**Closed by justparking** 2018-07-19 10:47 UTC
